### ISSUE TITLE
size of search graph is too small

### ISSUE THREAD

**Issue by viorelmd** [FirestonnneTFM/tfm_source_simplifier#1]
![image](https://user-images.githubusercontent.com/8680980/91905838-d0848880-ecaf-11ea-9cd8-23fbdfebbaa0.png)

**Comment by FirestonnneTFM** [comment]
I'm assuming that your issue is that you are running the program on the wrong swf.

Make sure to pull out the embedded swf in Transformice.swf, you can do this in two possible ways. Probably the easiest way if you are on windows is to use a swf memory dumper while running the game - just dump the largest >2MB swf file you see in memory. The other option is to use my extractor in the other repo: https://github.com/FirestonnneTFM/tfm_key_parser . Use the "dumper" program on Transformice.swf and it will give you the embedded swf.
